name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: roemer/jenkins-mirror-rewriter:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:  docker build -t $IMAGE_NAME .

    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker push
      run: docker push $IMAGE_NAME
    - name: Docker logout
      run: docker logout
